"""
AI Transformation Platform — Report Generator
Runs all agents and generates a Markdown report of enterprise findings.
"""

import sys
import os
import json
from datetime import datetime

# Adjust sys.path to find agents
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from agents.transformation_agents import AgentOrchestrator

def generate_report(results, output_file):
    """Generate a readable Markdown report from agent results."""
    
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    s = results["sludge_analysis"]
    c = results["champion_analysis"]
    co = results["coordination_analysis"]
    inn = results["innovation_analysis"]

    report_content = f"""# AI Transformation Scan Report
**Organization:** Enterprise
**Scan Discovery Date:** {timestamp}
---

## 🧹 Administrative Sludge Detection
**Total Annual Waste Potential:** {s['estimated_annual_savings_at_90_per_hour']}
**Waste Hours per Week:** {s['total_sludge_hours_per_week']}
**Worst Category:** {s['worst_category']}

### 🛑 Top 5 Sludge Targets
"""
    for t in s["top_5_targets"]:
        report_content += f"- **{t['task']}**: {t['hours_week']} hrs/week ({t['employees']} employees affected) · Impact Score: {t['impact_score']}\n"

    report_content += f"""
---

## 🏆 AI Champion Identification
**Champions Identified:** {c['total_champions_identified']}
**Top Champion:** {c['top_champion']}

| Name | Department | Score | Ideas Implemented |
|------|------------|-------|-------------------|
"""
    for ch in c["top_5"]:
        report_content += f"| {ch['name']} | {ch['dept']} | {ch['score']} | {ch['ideas_implemented']} |\n"

    report_content += f"""
---

## 🔗 Coordination Friction & Toggle Tax
**Workflows Audited:** {co['total_workflows_audited']}
**Unique Tools in Use:** {co['unique_tools_in_use']}
**Total Toggle Switches/Cycle:** {co['total_toggle_switches']}
**Avg Handoff Latency:** {co['avg_handoff_latency_hours']} hrs

### 🐢 Slowest Workflows
- **{co['slowest_workflow']}**
- **Super-agent consolidation targets:** {', '.join(co['super_agent_consolidation_targets'][:5])}

---

## 🧪 Innovation & AI Washing Defense
**Portfolio Size:** {inn['total_experiments']} experiments
**Production Success Rate:** {inn['production_success_rate']}
**AI Theater (Washing) Rate:** {inn['theater_rate']}

### ⚠️ Flagged for Strategic Review
"""
    for f in inn["flagged_for_review"]:
        report_content += f"- **{f['name']}** ({f['team']}): AI Washing Score {f['washing_score']}/5 · {f['roi']}\n"

    report_content += "\n---\n*Report generated by AI Transformation Platform — Baseline 1.0*"

    with open(output_file, 'w') as f:
        f.write(report_content)
    
    print(f"✅ Report generated successfully: {output_file}")

if __name__ == "__main__":
    print("🤖 Running AI Transformation Agents...")
    orch = AgentOrchestrator()
    results = orch.run_all()
    
    report_file = os.path.join(os.getcwd(), "enterprise_scan_report.md")
    generate_report(results, report_file)
