#!/usr/bin/env python3
"""
run_audit_report.py

Simulates parsing the audit logs generated by the governance platform
to detect anomalies, blocked requests, and PII exposure attempts.
"""

import json
import os
from collections import Counter
from datetime import datetime

def generate_report():
    print("="*60)
    print("🛡️  AI GOVERNANCE AUDIT REPORT")
    print(f"📅 Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("="*60)
    
    # Simulate log parsing
    # In a real scenario, this would read from S3/CloudWatch logs in JSONL format
    mock_logs = [
        {"timestamp": "10:01", "user_id": "u-123", "risk_tier": "High", "blocked": False},
        {"timestamp": "10:05", "user_id": "u-124", "risk_tier": "High", "blocked": True, "reason": "PII Detected"},
        {"timestamp": "10:08", "user_id": "u-125", "risk_tier": "Low", "blocked": False},
        {"timestamp": "10:12", "user_id": "u-123", "risk_tier": "High", "blocked": True, "reason": "Prompt Injection"},
        {"timestamp": "10:15", "user_id": "u-126", "risk_tier": "Low", "blocked": False},
        {"timestamp": "10:18", "user_id": "u-124", "risk_tier": "High", "blocked": True, "reason": "Restricted Tool Call"},
    ]
    
    total_requests = len(mock_logs)
    blocked_requests = [log for log in mock_logs if log.get("blocked")]
    
    print(f"\n📊 SUMMARY:")
    print(f"Total Requests Processed: {total_requests}")
    print(f"Total Requests Blocked:   {len(blocked_requests)} ({(len(blocked_requests)/total_requests)*100:.1f}%)")
    
    print("\n🚨 BLOCKING REASONS:")
    reasons = Counter(log.get("reason") for log in blocked_requests)
    for reason, count in reasons.items():
        print(f" - {reason}: {count}")
    
    print("\n🔍 ANOMALY DETECTION:")
    users = Counter(log.get("user_id") for log in blocked_requests)
    top_violator = users.most_common(1)
    if top_violator:
        print(f"⚠️ User {top_violator[0][0]} triggered {top_violator[0][1]} blocks. Flagging for review.")
    
    print("\nReport complete. Detailed JSON exported to s3://enterprise-ai-audit-logs/reports/")
    print("="*60)

if __name__ == "__main__":
    generate_report()
